#!/usr/bin/env bash
# scrub.sh — deterministic secret redaction over the bundle's copied files.
# Replaces matched secrets with [REDACTED] IN PLACE (only inside the bundle copy,
# never the originals) and writes a per-file report. Sourced by claude-bundler.sh.
#
# Uses perl for reliable cross-platform in-place regex substitution.

scrub_dir() {
  local dir="$1" report="$2"
  command -v perl >/dev/null 2>&1 || { echo "perl required for scrubbing" >&2; return 1; }

  : > "$report"
  {
    echo "# Secrets Report"
    echo
    echo "Generated by Claude Bundler Kit. Each row is a redaction made in the"
    echo "**bundle copy** (your originals are untouched). Review before sharing."
    echo
    echo "| File | Redactions |"
    echo "|------|------------|"
  } >> "$report"

  local total=0
  while IFS= read -r -d '' f; do
    # Skip binary files.
    if perl -ne 'exit 1 if -B $ARGV; exit 0;' "$f" 2>/dev/null; then :; fi
    file "$f" 2>/dev/null | grep -qiE 'text|json|ascii|empty' || continue

    local count
    perl -0777 -i -pe '
      my $n = 0;
      # Private key blocks
      $n += s/-----BEGIN [^-]*PRIVATE KEY-----.*?-----END [^-]*PRIVATE KEY-----/[REDACTED:PRIVATE_KEY]/gs;
      # Anthropic
      $n += s/sk-ant-[A-Za-z0-9_\-]{20,}/[REDACTED:ANTHROPIC_KEY]/g;
      # OpenAI (incl project keys)
      $n += s/sk-(proj-)?[A-Za-z0-9_\-]{20,}/[REDACTED:OPENAI_KEY]/g;
      # GitHub tokens
      $n += s/(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{30,}/[REDACTED:GITHUB_TOKEN]/g;
      $n += s/github_pat_[A-Za-z0-9_]{50,}/[REDACTED:GITHUB_PAT]/g;
      # AWS
      $n += s/AKIA[0-9A-Z]{16}/[REDACTED:AWS_KEY]/g;
      # Google API
      $n += s/AIza[0-9A-Za-z_\-]{35}/[REDACTED:GOOGLE_KEY]/g;
      # Slack
      $n += s/xox[baprs]-[A-Za-z0-9\-]{10,}/[REDACTED:SLACK_TOKEN]/g;
      # JWTs
      $n += s/eyJ[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}/[REDACTED:JWT]/g;
      # Bearer headers
      $n += s/(Bearer\s+)[A-Za-z0-9._\-]{12,}/${1}[REDACTED:BEARER]/g;
      # Generic KEY=VALUE / KEY: VALUE where key name looks sensitive
      $n += s/((?i)[A-Za-z0-9_\-]*(token|secret|password|passwd|api[_-]?key|access[_-]?key|client[_-]?secret|private[_-]?key)[A-Za-z0-9_\-]*\s*[:=]\s*["\x27]?)[^\s"\x27\n,}]+/${1}[REDACTED]/g;
      # Email addresses
      $n += s/[A-Za-z0-9._%+\-]+\@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}/[REDACTED:EMAIL]/g;
      print STDERR "$n\n";
    ' "$f" 2>/tmp/_scrub_n
    read -r count </tmp/_scrub_n 2>/dev/null || count=0
    count=${count:-0}
    if [ "$count" -gt 0 ] 2>/dev/null; then
      echo "| ${f#"$dir"/} | $count |" >> "$report"
      total=$((total + count))
    fi
  done < <(find "$dir" -type f -print0 2>/dev/null)

  rm -f /tmp/_scrub_n
  {
    echo
    echo "**Total redactions: $total**"
    echo
    if [ "$total" -eq 0 ]; then
      echo "No secrets matched the known patterns. Still skim the files manually —"
      echo "the scrubber catches common formats, not every possible secret."
    else
      echo "Skim the redacted files once before sharing to confirm coverage."
    fi
  } >> "$report"

  echo "  $total secret(s) redacted across the bundle."
}
