#!/usr/bin/env bash
# scrub.sh — deterministic secret + PII redaction over the bundle's copied files.
# Edits ONLY the bundle copies (never originals) and writes a per-file report.
# Sourced by claude-bundler.sh. Uses perl for reliable in-place substitution.

scrub_dir() {
  local dir="$1" report="$2"
  command -v perl >/dev/null 2>&1 || { echo "perl required for scrubbing" >&2; return 1; }

  # Home-path prefix to tokenize (hide the username without over-matching).
  local me="${USER:-$(id -un 2>/dev/null)}"

  : > "$report"
  {
    echo "# Secrets & PII Report"
    echo
    echo "Generated by Claude Bundler Kit. Each row is a redaction made in the"
    echo "**bundle copy** (your originals are untouched). Review before sharing."
    echo
    echo "Covered: API keys/tokens (incl. JSON env blocks), private keys, JWTs,"
    echo "bearer headers, passwords, emails, internal IPs, private hostnames,"
    echo "phone numbers, AWS account IDs in ARNs, and your home-path username."
    echo
    echo "| File | Redactions |"
    echo "|------|------------|"
  } >> "$report"

  local total=0 count
  while IFS= read -r -d '' f; do
    file "$f" 2>/dev/null | grep -qiE 'text|json|ascii|empty|script' || continue

    SCRUB_HOME="$HOME" SCRUB_USER="$me" perl -0777 -i -pe '
      my $n = 0;
      my $home = quotemeta($ENV{SCRUB_HOME} // "");
      my $user = $ENV{SCRUB_USER} // "";
      # --- secrets ---
      $n += s/-----BEGIN [^-]*PRIVATE KEY-----.*?-----END [^-]*PRIVATE KEY-----/[REDACTED:PRIVATE_KEY]/gs;
      $n += s/sk-ant-[A-Za-z0-9_\-]{20,}/[REDACTED:ANTHROPIC_KEY]/g;
      $n += s/sk-(proj-)?[A-Za-z0-9_\-]{20,}/[REDACTED:OPENAI_KEY]/g;
      $n += s/(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{30,}/[REDACTED:GITHUB_TOKEN]/g;
      $n += s/github_pat_[A-Za-z0-9_]{50,}/[REDACTED:GITHUB_PAT]/g;
      $n += s/AKIA[0-9A-Z]{16}/[REDACTED:AWS_KEY]/g;
      $n += s/AIza[0-9A-Za-z_\-]{35}/[REDACTED:GOOGLE_KEY]/g;
      $n += s/xox[baprs]-[A-Za-z0-9\-]{10,}/[REDACTED:SLACK_TOKEN]/g;
      $n += s/eyJ[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}\.[A-Za-z0-9_\-]{8,}/[REDACTED:JWT]/g;
      $n += s/(Bearer\s+)[A-Za-z0-9._\-]{12,}/${1}[REDACTED:BEARER]/g;
      # JSON-quoted sensitive key: "GITHUB_TOKEN": "value"
      $n += s/("[^"]*(?i:token|secret|password|passwd|api[_-]?key|access[_-]?key|client[_-]?secret|private[_-]?key)[^"]*"\s*:\s*")[^"]+"/${1}[REDACTED]"/g;
      # Generic KEY=VALUE / KEY: VALUE with sensitive key name
      $n += s/((?i)[A-Za-z0-9_\-]*(?:token|secret|password|passwd|api[_-]?key|access[_-]?key|client[_-]?secret|private[_-]?key)[A-Za-z0-9_\-]*\s*[:=]\s*["\x27]?)[^\s"\x27\n,}]+/${1}[REDACTED]/g;
      # --- PII / infra ---
      $n += s/[A-Za-z0-9._%+\-]+\@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}/[REDACTED:EMAIL]/g;
      $n += s/\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3})\b/[REDACTED:INTERNAL_IP]/g;
      $n += s/\b[a-z0-9][a-z0-9\-]*\.(?:local|lan|internal|home|corp)\b/[REDACTED:PRIVATE_HOST]/g;
      $n += s/arn:aws:[^:]*:[^:]*:(\d{12}):/arn:aws:::[REDACTED:AWS_ACCT]:/g;
      $n += s/(?<!\d)(?:\+?1[\s.\-]?)?\(?\d{3}\)?[\s.\-]\d{3}[\s.\-]\d{4}(?!\d)/[REDACTED:PHONE]/g;
      # --- identity: tokenize home path username ---
      if ($home) { $n += s/$home/\/home\/<USER>/g; }
      if ($user && length($user) >= 3) { $n += s/\/(?:home|Users)\/\Q$user\E\b/\/home\/<USER>/g; }
      print STDERR "$n\n";
    ' "$f" 2>/tmp/_scrub_n
    read -r count </tmp/_scrub_n 2>/dev/null || count=0
    count=${count:-0}
    if [ "$count" -gt 0 ] 2>/dev/null; then
      echo "| ${f#"$dir"/} | $count |" >> "$report"
      total=$((total + count))
    fi
  done < <(find "$dir" -type f -print0 2>/dev/null)

  rm -f /tmp/_scrub_n
  {
    echo
    echo "**Total redactions: $total**"
    echo
    if [ "$total" -eq 0 ]; then
      echo "Nothing matched the known patterns. Still skim the files manually —"
      echo "the scrubber catches common formats, not every possible secret."
    else
      echo "Skim the redacted files once before sharing to confirm coverage."
    fi
  } >> "$report"

  echo "  $total item(s) redacted across the bundle."
}
